### PR TITLE
Ubuntu, linux support

### PR DESCRIPTION
**Pull request by sid137**
Hi,

   I had some problems getting this to work on linux, so made some changes.  It wasn't restarting the server at all.

-Sidney

### CODE REVIEW

**Comment by johnbintz** [comment]
That looks good. Think you can refactor the code in `unmanaged_pid` a bit more to remove the duplication? There isn't much difference between the two codepaths, so any refactoring would be very nice to have. :)

**Comment by sid137** [comment]
ok, changed...  you might be able to simply use lsof -i :#{port}   as well on mac too..

**Comment by johnbintz** [comment]
Nope, no dice on `lsof -i` on Mac OS X. Still need `lsof -P`...though you might want to tack on the `-n` option to both `lsof` calls to get rid of rDNS on both systems and to speed it up (I decided to fire up a local Linux box to check that command. :) ).

**Comment by johnbintz** [comment]
I was wrong, `lsof -i` is fine. That's what I get for doing this stuff too late at night. Try the `linux-support` branch. It incorporates your change and gets it working on both OSes:

https://github.com/johnbintz/guard-rails/tree/linux-support

**Pull request merged**
